/**
 * Icon catalogue for the whole app. Two families are supported:
 *
 * - `ra` — RPG Awesome glyphs (font-based, fantasy/RPG themed). Rendered as `<i class="ra ra-*">`.
 * - `lu` — Lucide Angular components (stroke SVG, UI/general purpose). Rendered as a component.
 *
 * Anything the GM picks is stored on the entity as an `iconId` string:
 * `ra:crossed-swords`, `lu:shield`, etc. Legacy emoji strings are mapped through
 * {@link LEGACY_EMOJI_ICONS} so existing data keeps rendering.
 */

export type IconFamily = 'ra' | 'lu';

export interface IconOption {
  /** Canonical id, e.g. `ra:crossed-swords` or `lu:shield`. */
  readonly id: string;
  readonly family: IconFamily;
  /** RPG Awesome class suffix or Lucide component key. */
  readonly name: string;
  /** Human-readable label for pickers and screen readers. */
  readonly label: string;
  /** Grouping used to organise the picker. */
  readonly group: string;
}

/**
 * Curated RPG Awesome glyphs, grouped so the picker stays navigable. The full set has
 * ~500 icons; this selection covers the entities the shield models.
 */
export const RPG_ICONS: readonly IconOption[] = [
  // People & creatures
  ...ra('aura', 'Aura', 'People'),
  ...ra('aware', 'Aware', 'People'),
  ...ra('double-team', 'Double Team', 'People'),
  ...ra('falling', 'Falling', 'People'),
  ...ra('monster-skull', 'Monster Skull', 'People'),
  ...ra('muscle-fat', 'Muscle Fat', 'People'),
  ...ra('muscle-up', 'Muscle Up', 'People'),
  ...ra('player', 'Player', 'People'),
  ...ra('player-despair', 'Player Despair', 'People'),
  ...ra('player-dodge', 'Player Dodge', 'People'),
  ...ra('player-king', 'Player King', 'People'),
  ...ra('player-lift', 'Player Lift', 'People'),
  ...ra('player-pain', 'Player Pain', 'People'),
  ...ra('player-pyromaniac', 'Player Pyromaniac', 'People'),
  ...ra('player-shot', 'Player Shot', 'People'),
  ...ra('player-teleport', 'Player Teleport', 'People'),
  ...ra('player-thunder-struck', 'Player Thunder Struck', 'People'),

  // Combat & items
  ...ra('arcane-mask', 'arcane-mask', 'Combat'),
  ...ra('all-for-one', 'all-for-one', 'Combat'),
  ...ra('anvil', 'anvil', 'Combat'),
  ...ra('archer', 'archer', 'Combat'),
  ...ra('archery-target', 'archery-target', 'Combat'),
  ...ra('arena', 'arena', 'Combat'),
  ...ra('arrow-cluster', 'arrow-cluster', 'Combat'),
  ...ra('arrow-flights', 'arrow-flights', 'Combat'),
  ...ra('axe', 'axe', 'Combat'),
  ...ra('axe-swing', 'axe-swing', 'Combat'),
  ...ra('barbed-arrow', 'barbed-arrow', 'Combat'),
  ...ra('barrier', 'barrier', 'Combat'),
  ...ra('bat-sword', 'bat-sword', 'Combat'),
  ...ra('battered-axe', 'battered-axe', 'Combat'),
  ...ra('beam-wake', 'beam-wake', 'Combat'),
  ...ra('bear-trap', 'bear-trap', 'Combat'),
  ...ra('bolt-shield', 'bolt-shield', 'Combat'),
  ...ra('bomb-explosion', 'bomb-explosion', 'Combat'),
  ...ra('bombs', 'bombs', 'Combat'),
  ...ra('bone-knife', 'bone-knife', 'Combat'),
  ...ra('boomerang', 'boomerang', 'Combat'),
  ...ra('boot-stomp', 'boot-stomp', 'Combat'),
  ...ra('bowie-knife', 'bowie-knife', 'Combat'),
  ...ra('broadhead-arrow', 'broadhead-arrow', 'Combat'),
  ...ra('broken-bone', 'broken-bone', 'Combat'),
  ...ra('broken-shield', 'broken-shield', 'Combat'),
  ...ra('bullets', 'bullets', 'Combat'),
  ...ra('cannon-shot', 'cannon-shot', 'Combat'),
  ...ra('chemical-arrow', 'chemical-arrow', 'Combat'),
  ...ra('chain', 'chain', 'Combat'),
  ...ra('circular-saw', 'circular-saw', 'Combat'),
  ...ra('circular-shield', 'circular-shield', 'Combat'),
  ...ra('cluster-bomb', 'cluster-bomb', 'Combat'),
  ...ra('cracked-helm', 'cracked-helm', 'Combat'),
  ...ra('cracked-shield', 'cracked-shield', 'Combat'),
  ...ra('croc-sword', 'croc-sword', 'Combat'),
  ...ra('crossbow', 'crossbow', 'Combat'),
  ...ra('crossed-axes', 'crossed-axes', 'Combat'),
  ...ra('crossed-bones', 'crossed-bones', 'Combat'),
  ...ra('crossed-pistols', 'crossed-pistols', 'Combat'),
  ...ra('crossed-swords', 'crossed-swords', 'Combat'),
  ...ra('daggers', 'daggers', 'Combat'),
  ...ra('dervish-swords', 'dervish-swords', 'Combat'),
  ...ra('diving-dagger', 'diving-dagger', 'Combat'),
  ...ra('drill', 'drill', 'Combat'),
  ...ra('dripping-blade', 'dripping-blade', 'Combat'),
  ...ra('dripping-knife', 'dripping-knife', 'Combat'),
  ...ra('dripping-sword', 'dripping-sword', 'Combat'),
  ...ra('duel', 'duel', 'Combat'),
  ...ra('explosion', 'explosion', 'Combat'),
  ...ra('explosive-materials', 'explosive-materials', 'Combat'),
  ...ra('eye-shield', 'eye-shield', 'Combat'),
  ...ra('fire-bomb', 'fire-bomb', 'Combat'),
  ...ra('fire-shield', 'fire-shield', 'Combat'),
  ...ra('fireball-sword', 'fireball-sword', 'Combat'),
  ...ra('flaming-arrow', 'flaming-arrow', 'Combat'),
  ...ra('flaming-claw', 'flaming-claw', 'Combat'),
  ...ra('flaming-trident', 'flaming-trident', 'Combat'),
  ...ra('flat-hammer', 'flat-hammer', 'Combat'),
  ...ra('frozen-arrow', 'frozen-arrow', 'Combat'),
  ...ra('gavel', 'gavel', 'Combat'),
  ...ra('gear-hammer', 'gear-hammer', 'Combat'),
  ...ra('grappling-hook', 'grappling-hook', 'Combat'),
  ...ra('grenade', 'grenade', 'Combat'),
  ...ra('guillotine', 'guillotine', 'Combat'),
  ...ra('halberd', 'halberd', 'Combat'),
  ...ra('hammer', 'hammer', 'Combat'),
  ...ra('hammer-drop', 'hammer-drop', 'Combat'),
  ...ra('hand-saw', 'hand-saw', 'Combat'),
  ...ra('harpoon-trident', 'harpoon-trident', 'Combat'),
  ...ra('helmet', 'helmet', 'Combat'),
  ...ra('horns', 'horns', 'Combat'),
  ...ra('heavy-shield', 'heavy-shield', 'Combat'),
  ...ra('implosion', 'implosion', 'Combat'),
  ...ra('jetpack', 'jetpack', 'Combat'),
  ...ra('kitchen-knives', 'kitchen-knives', 'Combat'),
  ...ra('knife', 'knife', 'Combat'),
  ...ra('knight-helmet', 'knight-helmet', 'Combat'),
  ...ra('kunai', 'kunai', 'Combat'),
  ...ra('large-hammer', 'large-hammer', 'Combat'),
  ...ra('laser-blast', 'laser-blast', 'Combat'),
  ...ra('lightning-sword', 'lightning-sword', 'Combat'),
  ...ra('mass-driver', 'mass-driver', 'Combat'),
  ...ra('mp5', 'mp5', 'Combat'),
  ...ra('musket', 'musket', 'Combat'),
  ...ra('plain-dagger', 'plain-dagger', 'Combat'),
  ...ra('relic-blade', 'relic-blade', 'Combat'),
  ...ra('revolver', 'revolver', 'Combat'),
  ...ra('rifle', 'rifle', 'Combat'),
  ...ra('round-shield', 'round-shield', 'Combat'),
  ...ra('scythe', 'scythe', 'Combat'),
  ...ra('shield', 'shield', 'Combat'),
  ...ra('shuriken', 'shuriken', 'Combat'),
  ...ra('sickle', 'sickle', 'Combat'),
  ...ra('spear-head', 'spear-head', 'Combat'),
  ...ra('spikeball', 'spikeball', 'Combat'),
  ...ra('spiked-mace', 'spiked-mace', 'Combat'),
  ...ra('spinning-sword', 'spinning-sword', 'Combat'),
  ...ra('supersonic-arrow', 'supersonic-arrow', 'Combat'),
  ...ra('sword', 'sword', 'Combat'),
  ...ra('target-arrows', 'target-arrows', 'Combat'),
  ...ra('target-laser', 'target-laser', 'Combat'),
  ...ra('thorn-arrow', 'thorn-arrow', 'Combat'),
  ...ra('thorny-vine', 'thorny-vine', 'Combat'),
  ...ra('trident', 'trident', 'Combat'),
  ...ra('vest', 'vest', 'Combat'),
  ...ra('vine-whip', 'vine-whip', 'Combat'),
  ...ra('zebra-shield', 'zebra-shield', 'Combat'),

  // Magic & arcane
  ...ra('brain-freeze', 'brain-freeze', 'Magic'),
  ...ra('burning-book', 'burning-book', 'Magic'),
  ...ra('burning-embers', 'burning-embers', 'Magic'),
  ...ra('burning-eye', 'burning-eye', 'Magic'),
  ...ra('burst-blob', 'burst-blob', 'Magic'),
  ...ra('cold-heart', 'cold-heart', 'Magic'),
  ...ra('crystal-ball', 'crystal-ball', 'Magic'),
  ...ra('crystal-cluster', 'crystal-cluster', 'Magic'),
  ...ra('crystal-wand', 'crystal-wand', 'Magic'),
  ...ra('crystals', 'crystals', 'Magic'),
  ...ra('diamond', 'diamond', 'Magic'),
  ...ra('divert', 'divert', 'Magic'),
  ...ra('doubled', 'doubled', 'Magic'),
  ...ra('dragon-breath', 'dragon-breath', 'Magic'),
  ...ra('droplet', 'droplet', 'Magic'),
  ...ra('droplet-splash', 'droplet-splash', 'Magic'),
  ...ra('emerald', 'emerald', 'Magic'),
  ...ra('eyeball', 'eyeball', 'Magic'),
  ...ra('fairy-wand', 'fairy-wand', 'Magic'),
  ...ra('fire-breath', 'fire-breath', 'Magic'),
  ...ra('fire-ring', 'fire-ring', 'Magic'),
  ...ra('fire-symbol', 'fire-symbol', 'Magic'),
  ...ra('flame-symbol', 'flame-symbol', 'Magic'),
  ...ra('frost-emblem', 'frost-emblem', 'Magic'),
  ...ra('frostfire', 'frostfire', 'Magic'),
  ...ra('gem', 'gem', 'Magic'),
  ...ra('gem-pendant', 'gem-pendant', 'Magic'),
  ...ra('gloop', 'gloop', 'Magic'),
  ...ra('gold-bar', 'gold-bar', 'Magic'),
  ...ra('health', 'health', 'Magic'),
  ...ra('health-decrease', 'health-decrease', 'Magic'),
  ...ra('health-increase', 'health-increase', 'Magic'),
  ...ra('hospital-cross', 'hospital-cross', 'Magic'),
  ...ra('hot-surface', 'hot-surface', 'Magic'),
  ...ra('hydra-shot', 'hydra-shot', 'Magic'),
  ...ra('incense', 'incense', 'Magic'),
  ...ra('kaleidoscope', 'kaleidoscope', 'Magic'),
  ...ra('lava', 'lava', 'Magic'),
  ...ra('level-four', 'level-four', 'Magic'),
  ...ra('level-four-advanced', 'level-four-advanced', 'Magic'),
  ...ra('level-three', 'level-three', 'Magic'),
  ...ra('level-three-advanced', 'level-three-advanced', 'Magic'),
  ...ra('level-two', 'level-two', 'Magic'),
  ...ra('level-two-advanced', 'level-two-advanced', 'Magic'),
  ...ra('lightning', 'lightning', 'Magic'),
  ...ra('lightning-bolt', 'lightning-bolt', 'Magic'),
  ...ra('lightning-storm', 'lightning-storm', 'Magic'),
  ...ra('lightning-trio', 'lightning-trio', 'Magic'),
  ...ra('sapphire', 'sapphire', 'Magic'),
  ...ra('small-fire', 'small-fire', 'Magic'),
  ...ra('snowflake', 'snowflake', 'Magic'),
  ...ra('sun', 'sun', 'Magic'),
  ...ra('sun-symbol', 'sun-symbol', 'Magic'),
  ...ra('sunbeams', 'sunbeams', 'Magic'),
  ...ra('triforce', 'triforce', 'Magic'),
  ...ra('two-hearts', 'two-hearts', 'Magic'),
  ...ra('water-drop', 'water-drop', 'Magic'),


  // Places & travel
  ...ra('ankh', 'ankh', 'Rpg'),
  ...ra('angel-wings', 'angel-wings', 'Rpg'),
  ...ra('anchor', 'anchor', 'Rpg'),
  ...ra('batwings', 'batwings', 'Rpg'),
  ...ra('bell', 'bell', 'Rpg'),
  ...ra('bird-mask', 'bird-mask', 'Rpg'),
  ...ra('bowling-pin', 'bowling-pin', 'Rpg'),
  ...ra('bridge', 'bridge', 'Rpg'),
  ...ra('broken-skull', 'broken-skull', 'Rpg'),
  ...ra('campfire', 'campfire', 'Rpg'),
  ...ra('candle-fire', 'candle-fire', 'Rpg'),
  ...ra('capitol', 'capitol', 'Rpg'),
  ...ra('castle-emblem', 'castle-emblem', 'Rpg'),
  ...ra('circle-of-circles', 'circle-of-circles', 'Rpg'),
  ...ra('crowned-heart', 'crowned-heart', 'Rpg'),
  ...ra('cubes', 'cubes', 'Rpg'),
  ...ra('cut-palm', 'cut-palm', 'Rpg'),
  ...ra('cycle', 'cycle', 'Rpg'),
  ...ra('death-skull', 'death-skull', 'Rpg'),
  ...ra('demolish', 'demolish', 'Rpg'),
  ...ra('desert-skull', 'desert-skull', 'Rpg'),
  ...ra('dragon-wing', 'dragon-wing', 'Rpg'),
  ...ra('feather-wing', 'feather-wing', 'Rpg'),
  ...ra('feathered-wing', 'feathered-wing', 'Rpg'),
  ...ra('fedora', 'fedora', 'Rpg'),
  ...ra('fluffy-swirl', 'fluffy-swirl', 'Rpg'),
  ...ra('footprint', 'footprint', 'Rpg'),
  ...ra('forging', 'forging', 'Rpg'),
  ...ra('forward', 'forward', 'Rpg'),
  ...ra('glass-heart', 'glass-heart', 'Rpg'),
  ...ra('groundbreaker', 'groundbreaker', 'Rpg'),
  ...ra('guarded-tower', 'guarded-tower', 'Rpg'),
  ...ra('hand', 'hand', 'Rpg'),
  ...ra('hand-emblem', 'hand-emblem', 'Rpg'),
  ...ra('heart-tower', 'heart-tower', 'Rpg'),
  ...ra('heavy-fall', 'heavy-fall', 'Rpg'),
  ...ra('help', 'help', 'Rpg'),
  ...ra('hive-emblem', 'hive-emblem', 'Rpg'),
  ...ra('hole-ladder', 'hole-ladder', 'Rpg'),
  ...ra('hood', 'hood', 'Rpg'),
  ...ra('horn-call', 'horn-call', 'Rpg'),
  ...ra('interdiction', 'interdiction', 'Rpg'),
  ...ra('locked-fortress', 'locked-fortress', 'Rpg'),
  ...ra('meat-hook', 'meat-hook', 'Rpg'),
  ...ra('metal-gate', 'metal-gate', 'Rpg'),
  ...ra('mine-wagon', 'mine-wagon', 'Rpg'),
  ...ra('mining-diamonds', 'mining-diamonds', 'Rpg'),
  ...ra('mountains', 'mountains', 'Rpg'),
  ...ra('nodular', 'nodular', 'Rpg'),
  ...ra('ocean-emblem', 'ocean-emblem', 'Rpg'),
  ...ra('omega', 'omega', 'Rpg'),
  ...ra('on-target', 'on-target', 'Rpg'),
  ...ra('ophiuchus', 'ophiuchus', 'Rpg'),
  ...ra('overhead', 'overhead', 'Rpg'),
  ...ra('overmind', 'overmind', 'Rpg'),
  ...ra('pawprint', 'pawprint', 'Rpg'),
  ...ra('podium', 'podium', 'Rpg'),
  ...ra('pyramids', 'pyramids', 'Rpg'),
  ...ra('queen-crown', 'queen-crown', 'Rpg'),
  ...ra('radial-balance', 'radial-balance', 'Rpg'),
  ...ra('reverse', 'reverse', 'Rpg'),
  ...ra('scroll-unfurled', 'scroll-unfurled', 'Rpg'),
  ...ra('shoe-prints', 'shoe-prints', 'Rpg'),
  ...ra('shot-through-the-heart', 'shot-through-the-heart', 'Rpg'),
  ...ra('shovel', 'shovel', 'Rpg'),
  ...ra('sideswipe', 'sideswipe', 'Rpg'),
  ...ra('site', 'site', 'Rpg'),
  ...ra('skull', 'skull', 'Rpg'),
  ...ra('skull-trophy', 'skull-trophy', 'Rpg'),
  ...ra('spawn-node', 'spawn-node', 'Rpg'),
  ...ra('splash', 'splash', 'Rpg'),
  ...ra('targeted', 'targeted', 'Rpg'),
  ...ra('tic-tac-toe', 'tic-tac-toe', 'Rpg'),
  ...ra('tooth', 'tooth', 'Rpg'),
  ...ra('tower', 'tower', 'Rpg'),
  ...ra('trail', 'trail', 'Rpg'),
  ...ra('turd', 'turd', 'Rpg'),
  ...ra('uncertainty', 'uncertainty', 'Rpg'),
  ...ra('underhand', 'underhand', 'Rpg'),
  ...ra('x-mark', 'x-mark', 'Rpg'),

  // Treasure & tools
  ...ra('ammo-bag', 'ammo-bag', 'Items'),
  ...ra('alligator-clip', 'alligator-clip', 'Items'),
  ...ra('ball', 'ball', 'Items'),
  ...ra('book', 'book', 'Items'),
  ...ra('candle', 'candle', 'Items'),
  ...ra('castle-flag', 'castle-flag', 'Items'),
  ...ra('compass', 'compass', 'Items'),
  ...ra('crown', 'crown', 'Items'),
  ...ra('crown-of-thorns', 'crown-of-thorns', 'Items'),
  ...ra('horseshoe', 'horseshoe', 'Items'),
  ...ra('hourglass', 'hourglass', 'Items'),
  ...ra('jigsaw-piece', 'jigsaw-piece', 'Items'),
  ...ra('kettlebell', 'kettlebell', 'Items'),
  ...ra('key', 'key', 'Items'),
  ...ra('key-basic', 'key-basic', 'Items'),
  ...ra('lantern-flame', 'lantern-flame', 'Items'),
  ...ra('wrench', 'wrench', 'Items'),
  ...ra('lit-candelabra', 'lit-candelabra', 'Items'),
  ...ra('match', 'match', 'Items'),
  ...ra('medical-pack', 'medical-pack', 'Items'),
  ...ra('mirror', 'mirror', 'Items'),
  ...ra('moon-sun', 'moon-sun', 'Items'),
  ...ra('nails', 'nails', 'Items'),
  ...ra('noose', 'noose', 'Items'),
  ...ra('ocarina', 'ocarina', 'Items'),
  ...ra('pawn', 'pawn', 'Items'),
  ...ra('pill', 'pill', 'Items'),
  ...ra('pills', 'pills', 'Items'),
  ...ra('ping-pong', 'ping-pong', 'Items'),
  ...ra('potion', 'potion', 'Items'),
  ...ra('quill-ink', 'quill-ink', 'Items'),
  ...ra('ringing-bell', 'ringing-bell', 'Items'),
  ...ra('rune-stone', 'rune-stone', 'Items'),
  ...ra('sheriff', 'sheriff', 'Items'),
  ...ra('ship-emblem', 'ship-emblem', 'Items'),
  ...ra('shotgun-shell', 'shotgun-shell', 'Items'),
  ...ra('slash-ring', 'slash-ring', 'Items'),
  ...ra('snorkel', 'snorkel', 'Items'),
  ...ra('soccer-ball', 'soccer-ball', 'Items'),
  ...ra('spray', 'spray', 'Items'),
  ...ra('stopwatch', 'stopwatch', 'Items'),
  ...ra('syringe', 'syringe', 'Items'),
  ...ra('three-keys', 'three-keys', 'Items'),
  ...ra('torch', 'torch', 'Items'),
  ...ra('trophy', 'trophy', 'Items'),
  ...ra('wooden-sign', 'wooden-sign', 'Items'),

  // Nature & misc
  ...ra('acorn', 'acorn', 'Nature'),
  ...ra('apple', 'apple', 'Nature'),
  ...ra('beer', 'beer', 'Nature'),
  ...ra('brandy-bottle', 'brandy-bottle', 'Nature'),
  ...ra('carrot', 'carrot', 'Nature'),
  ...ra('cheese', 'cheese', 'Nature'),
  ...ra('chicken-leg', 'chicken-leg', 'Nature'),
  ...ra('coffee-mug', 'coffee-mug', 'Nature'),
  ...ra('crab-claw', 'crab-claw', 'Nature'),
  ...ra('egg', 'egg', 'Nature'),
  ...ra('egg-pod', 'egg-pod', 'Nature'),
  ...ra('eggplant', 'eggplant', 'Nature'),
  ...ra('honeycomb', 'honeycomb', 'Nature'),
  ...ra('ice-cube', 'ice-cube', 'Nature'),
  ...ra('knife-fork', 'knife-fork', 'Nature'),
  ...ra('meat', 'meat', 'Nature'),
  ...ra('roast-chicken', 'roast-chicken', 'Nature'),
  ...ra('toast', 'toast', 'Nature'),
  ...ra('clover', 'clover', 'Nature'),
  ...ra('daisy', 'daisy', 'Nature'),
  ...ra('dead-tree', 'dead-tree', 'Nature'),
  ...ra('flower', 'flower', 'Nature'),
  ...ra('flowers', 'flowers', 'Nature'),
  ...ra('grass', 'grass', 'Nature'),
  ...ra('grass-patch', 'grass-patch', 'Nature'),
  ...ra('leaf', 'leaf', 'Nature'),
  ...ra('palm-tree', 'palm-tree', 'Nature'),
  ...ra('pine-tree', 'pine-tree', 'Nature'),
  ...ra('sprout', 'sprout', 'Nature'),
  ...ra('sprout-emblem', 'sprout-emblem', 'Nature'),
  ...ra('super-mushroom', 'super-mushroom', 'Nature'),
  ...ra('trefoil-lily', 'trefoil-lily', 'Nature'),
  ...ra('zigzag-leaf', 'zigzag-leaf', 'Nature'),

  ...ra('acid', 'acid', 'Status'),
  ...ra('arson', 'arson', 'Status'),
  ...ra('biohazard', 'biohazard', 'Status'),
  ...ra('blade-bite', 'blade-bite', 'Status'),
  ...ra('blast', 'blast', 'Status'),
  ...ra('blaster', 'blaster', 'Status'),
  ...ra('bleeding-eye', 'bleeding-eye', 'Status'),
  ...ra('bleeding-hearts', 'bleeding-hearts', 'Status'),
  ...ra('bone-bite', 'bone-bite', 'Status'),
  ...ra('burning-meteor', 'burning-meteor', 'Status'),
  ...ra('crush', 'crush', 'Status'),
  ...ra('decapitation', 'decapitation', 'Status'),
  ...ra('fall-down', 'fall-down', 'Status'),
  ...ra('fire', 'fire', 'Status'),
  ...ra('food-chain', 'food-chain', 'Status'),
  ...ra('focused-lightning', 'focused-lightning', 'Status'),
  ...ra('heartburn', 'heartburn', 'Status'),
  ...ra('poison-cloud', 'poison-cloud', 'Status'),
  ...ra('tombstone', 'tombstone', 'Status'),
];

function ra(name: string, label: string, group: string): IconOption[] {
  return [{ id: `ra:${name}`, family: 'ra', name, label, group }];
}

/**
 * Lucide icons used across the UI chrome (buttons, status, navigation). These are picked as
 * concrete components by {@link IconComponent}; the name is the Lucide export without the
 * `Lucide` prefix, lower-cased.
 */
export const LUCIDE_ICONS: readonly IconOption[] = [
  ...lu('swords', 'Swords', 'Combat'),
  ...lu('sword', 'Sword', 'Combat'),
  ...lu('shield', 'Shield', 'Combat'),
  ...lu('axes', 'Axes', 'Combat'),
  ...lu('target', 'Target', 'Combat'),
  ...lu('crosshair', 'Crosshair', 'Combat'),
  ...lu('flame', 'Flame', 'Magic'),
  ...lu('sparkles', 'Sparkles', 'Magic'),
  ...lu('wand-sparkles', 'Wand', 'Magic'),
  ...lu('zap', 'Zap', 'Magic'),
  ...lu('snowflake', 'Snowflake', 'Magic'),
  ...lu('droplet', 'Droplet', 'Magic'),
  ...lu('leaf', 'Leaf', 'Magic'),
  ...lu('skull', 'Skull', 'People'),
  ...lu('ghost', 'Ghost', 'People'),
  ...lu('user', 'User', 'People'),
  ...lu('users', 'Users', 'People'),
  ...lu('user-round', 'Person', 'People'),
  ...lu('bot', 'Construct', 'People'),
  ...lu('crown', 'Crown', 'People'),
  ...lu('map', 'Map', 'Places'),
  ...lu('map-pin', 'Location', 'Places'),
  ...lu('castle', 'Castle', 'Places'),
  ...lu('tent', 'Camp', 'Places'),
  ...lu('mountain', 'Mountain', 'Places'),
  ...lu('trees', 'Forest', 'Places'),
  ...lu('house', 'House', 'Places'),
  ...lu('compass', 'Compass', 'Places'),
  ...lu('book', 'Book', 'Items'),
  ...lu('book-open', 'Book Open', 'Items'),
  ...lu('scroll', 'Scroll', 'Items'),
  ...lu('gem', 'Gem', 'Items'),
  ...lu('coins', 'Coins', 'Items'),
  ...lu('key', 'Key', 'Items'),
  ...lu('lock', 'Lock', 'Items'),
  ...lu('backpack', 'Backpack', 'Items'),
  ...lu('flask-conical', 'Flask', 'Items'),
  ...lu('heart', 'Heart', 'Status'),
  ...lu('heart-pulse', 'Vitality', 'Status'),
  ...lu('activity', 'Activity', 'Status'),
  ...lu('star', 'Star', 'Status'),
  ...lu('eye', 'Eye', 'Status'),
  ...lu('bell', 'Alert', 'Status'),
  ...lu('folder', 'Folder', 'Organisation'),
  ...lu('tags', 'Tags', 'Organisation'),
  ...lu('notebook', 'Notebook', 'Organisation'),
  ...lu('file-text', 'Note', 'Organisation'),
  ...lu('list', 'List', 'Organisation'),
  ...lu('grid', 'Grid', 'Organisation'),
  ...lu('clock', 'Clock', 'Organisation'),
  ...lu('calendar', 'Calendar', 'Organisation'),
  ...lu('dices', 'Dice', 'Organisation'),
  ...lu('puzzle', 'Puzzle', 'Organisation'),
  ...lu('package', 'Package', 'Organisation'),
  ...lu('layers', 'Layers', 'Organisation'),
];

function lu(name: string, label: string, group: string): IconOption[] {
  return [{ id: `lu:${name}`, family: 'lu', name, label, group }];
}

/** Everything the picker can offer. */
export const ALL_ICONS: readonly IconOption[] = [...RPG_ICONS, ...LUCIDE_ICONS];

/** Icon id used when an entity has no explicit choice. */
export const DEFAULT_ICON_ID = 'lu:user';

/**
 * Legacy emoji → icon id, so entities authored before the icon system keep rendering.
 */
export const LEGACY_EMOJI_ICONS: Readonly<Record<string, string>> = {
  '🧝': 'ra:hood',
  '👹': 'ra:monster-skull',
  '👺': 'ra:broken-skull',
  '🐉': 'ra:dragon',
  '💀': 'ra:skull',
  '👻': 'ra:eye-monster',
  '🐺': 'ra:wolf-head',
  '🕷️': 'ra:spider-face',
  '🦇': 'ra:batwings',
  '🧙': 'ra:crystal-wand',
  '⚔️': 'ra:crossed-swords',
  '⚔': 'ra:crossed-swords',
  '🗡️': 'ra:plain-dagger',
  '🛡️': 'ra:shield',
  '🏹': 'ra:crossbow',
  '🪄': 'ra:fairy-wand',
  '✨': 'lu:sparkles',
  '🔥': 'ra:flame-symbol',
  '❄️': 'ra:ice-cube',
  '⚡': 'ra:lightning-bolt',
  '📖': 'ra:scroll-unfurled',
  '📚': 'ra:book',
  '📝': 'lu:notebook',
  '📄': 'lu:file-text',
  '🗂️': 'lu:folder',
  '🏰': 'lu:castle',
  '🗺️': 'lu:map',
  '🧭': 'lu:compass',
  '⏳': 'lu:clock',
  '📅': 'lu:calendar',
  '👥': 'lu:users',
  '👤': 'lu:user',
  '✎': 'lu:pencil',
  '✕': 'lu:x',
  '📌': 'lu:pin',
};

/**
 * Normalises any stored icon value into a renderable icon id. Accepts a canonical id,
 * a legacy emoji, or an empty value (falls back to a family default).
 */
export function resolveIconId(value: string | null | undefined, fallback = DEFAULT_ICON_ID): string {
  if (!value) return fallback;
  if (value.startsWith('ra:') || value.startsWith('lu:')) return value;
  return LEGACY_EMOJI_ICONS[value] ?? fallback;
}
