import {
  LucideActivity,
  LucideAlertTriangle,
  LucideArchive,
  LucideArrowLeft,
  LucideArrowRight,
  LucideAxe,
  LucideAward,
  LucideBackpack,
  LucideBell,
  LucideBook,
  LucideBookOpen,
  LucideBot,
  LucideCalendar,
  LucideCastle,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronUp,
  LucideClock,
  LucideCoins,
  LucideCompass,
  LucideCopy,
  LucideCrosshair,
  LucideCrown,
  LucideDices,
  LucideDownload,
  LucideDroplet,
  LucideEdit,
  LucideEye,
  LucideFileText,
  LucideFlame,
  LucideFlaskConical,
  LucideFolder,
  LucideFolderOpen,
  LucideGem,
  LucideGhost,
  LucideGrid,
  LucideHeart,
  LucideHeartPulse,
  LucideHouse,
  LucideKey,
  LucideLayers,
  LucideLeaf,
  LucideList,
  LucideLoader,
  LucideLock,
  LucideMap,
  LucideMapPin,
  LucideMaximize,
  LucideMinimize,
  LucideMinus,
  LucideMountain,
  LucideNotebook,
  LucidePackage,
  LucidePencil,
  LucidePin,
  LucidePlus,
  LucidePuzzle,
  LucideSave,
  LucideSearch,
  LucideSettings,
  LucideShield,
  LucideSkull,
  LucideSnowflake,
  LucideSparkles,
  LucideStar,
  LucideSword,
  LucideSwords,
  LucideTags,
  LucideTarget,
  LucideTent,
  LucideTrash,
  LucideTrees,
  LucideUpload,
  LucideUser,
  LucideUserRound,
  LucideUsers,
  LucideWandSparkles,
  LucideX,
  LucideZap,
  type LucideIcon,
} from '@lucide/angular';

/**
 * Lucide name → component. Only the icons the app actually references are imported so the
 * bundle stays small. Keys match the `name` part of a `lu:*` icon id.
 */
export const LUCIDE_COMPONENTS: Readonly<Record<string, LucideIcon>> = {
  activity: LucideActivity,
  'alert-triangle': LucideAlertTriangle,
  archive: LucideArchive,
  'arrow-left': LucideArrowLeft,
  'arrow-right': LucideArrowRight,
  axe: LucideAxe,
  award: LucideAward,
  backpack: LucideBackpack,
  bell: LucideBell,
  book: LucideBook,
  'book-open': LucideBookOpen,
  bot: LucideBot,
  calendar: LucideCalendar,
  castle: LucideCastle,
  check: LucideCheck,
  'chevron-down': LucideChevronDown,
  'chevron-left': LucideChevronLeft,
  'chevron-right': LucideChevronRight,
  'chevron-up': LucideChevronUp,
  clock: LucideClock,
  coins: LucideCoins,
  compass: LucideCompass,
  copy: LucideCopy,
  crosshair: LucideCrosshair,
  crown: LucideCrown,
  dices: LucideDices,
  download: LucideDownload,
  droplet: LucideDroplet,
  edit: LucideEdit,
  eye: LucideEye,
  'file-text': LucideFileText,
  flame: LucideFlame,
  'flask-conical': LucideFlaskConical,
  folder: LucideFolder,
  'folder-open': LucideFolderOpen,
  gem: LucideGem,
  ghost: LucideGhost,
  grid: LucideGrid,
  heart: LucideHeart,
  'heart-pulse': LucideHeartPulse,
  house: LucideHouse,
  key: LucideKey,
  layers: LucideLayers,
  leaf: LucideLeaf,
  list: LucideList,
  loader: LucideLoader,
  lock: LucideLock,
  map: LucideMap,
  'map-pin': LucideMapPin,
  maximize: LucideMaximize,
  minimize: LucideMinimize,
  minus: LucideMinus,
  mountain: LucideMountain,
  notebook: LucideNotebook,
  package: LucidePackage,
  pencil: LucidePencil,
  pin: LucidePin,
  plus: LucidePlus,
  puzzle: LucidePuzzle,
  save: LucideSave,
  search: LucideSearch,
  settings: LucideSettings,
  shield: LucideShield,
  skull: LucideSkull,
  snowflake: LucideSnowflake,
  sparkles: LucideSparkles,
  star: LucideStar,
  sword: LucideSword,
  swords: LucideSwords,
  tags: LucideTags,
  target: LucideTarget,
  tent: LucideTent,
  trash: LucideTrash,
  trees: LucideTrees,
  upload: LucideUpload,
  user: LucideUser,
  'user-round': LucideUserRound,
  users: LucideUsers,
  'wand-sparkles': LucideWandSparkles,
  x: LucideX,
  zap: LucideZap,
};

/** Icon components re-exported for the chrome (buttons, empty states). */
export {
  LucideActivity,
  LucideAlertTriangle,
  LucideArchive,
  LucideArrowLeft,
  LucideArrowRight,
  LucideAxe,
  LucideBackpack,
  LucideBell,
  LucideBook,
  LucideBookOpen,
  LucideBot,
  LucideCalendar,
  LucideCastle,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronUp,
  LucideClock,
  LucideCoins,
  LucideCompass,
  LucideCopy,
  LucideCrosshair,
  LucideCrown,
  LucideDices,
  LucideDownload,
  LucideDroplet,
  LucideEdit,
  LucideEye,
  LucideFileText,
  LucideFlame,
  LucideFlaskConical,
  LucideFolder,
  LucideFolderOpen,
  LucideGem,
  LucideGhost,
  LucideGrid,
  LucideHeart,
  LucideHeartPulse,
  LucideHouse,
  LucideKey,
  LucideLayers,
  LucideLeaf,
  LucideList,
  LucideLoader,
  LucideLock,
  LucideMap,
  LucideMapPin,
  LucideMaximize,
  LucideMinimize,
  LucideMinus,
  LucideMountain,
  LucideNotebook,
  LucidePackage,
  LucidePencil,
  LucidePin,
  LucidePlus,
  LucidePuzzle,
  LucideSave,
  LucideSearch,
  LucideSettings,
  LucideShield,
  LucideSkull,
  LucideSnowflake,
  LucideSparkles,
  LucideStar,
  LucideSword,
  LucideSwords,
  LucideTags,
  LucideTarget,
  LucideTent,
  LucideTrash,
  LucideTrees,
  LucideUpload,
  LucideUser,
  LucideUserRound,
  LucideUsers,
  LucideWandSparkles,
  LucideX,
  LucideZap,
};
